myProject/mysite/Login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('acc/', views.GetAllApiView.as_view(), name='acc'),
    path('loginView/', views.login, name='login'),
]

myProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('poll.urls')),
    path('Login/', include('Login.urls')),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
]

myProject/mysite/news/urls.py
from django.urls import path
from . import views
app_name = 'news'
urlpatterns = [
    path('', views.new, name="news"),
    path('add/', views.post_News, name="add"),
    path('save/', views.save_news, name="save"),
]

myProject/mysite/poll/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('choice/<int:question_id>', views.vote, name='vote'),
    path('detail/<int:question_id>', views.detailView, name='detail'),
    path('list/', views.viewList, name='view-list'),
    path('check/', views.checkLogin, name='check-login'),
    path('login/', views.login, name='login'),
    path('', views.index, name='index'),

]

myProject/mysite/Login/models.py
from django.db import models


# Create your models here.
class Login(models.Model):
    user_name = models.CharField(max_length=50, blank=False, null=False)
    pass_word = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.user_name

myProject/mysite/news/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = models.TextField(max_length=100, blank=False, null=False)
    date_time = models.DateTimeField(default=timezone.datetime.now())

    def __str__(self):
        return self.title

myProject/mysite/poll/models.py
from django.db import models

# Create your models here.

from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Login(models.Model):
    user_name = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

    def __str__(self):
        return self.user_name

myProject/mysite/Login/views.py
import hashlib

from django.shortcuts import render
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import HttpResponse
from .models import Login
from .serializers import GetAllAccount, Account
# Create your views here.

def login(request):
    return render(request, "Login/loginView.html")

class GetAllApiView(APIView):

    def get(self, request):
        list_acc = Login.objects.all()
        dataAcc = GetAllAccount(list_acc, many=True)
        return Response(data=dataAcc.data, status=status.HTTP_200_OK)

    # tạo tài khoản
    # def post(self, request):
    #     dataPost = {'user_name': request.data['username'], 'pass_word': request.data['password']}
    #     mydata = Account(data=dataPost)
    #     if not mydata.is_valid():
    #         return Response("data is not validate ", status=status.HTTP_400_BAD_REQUEST)
    #     userName = mydata.data['user_name']
    #     passWord = mydata.data['pass_word']
    #     datafilter = Login.objects.filter(user_name=userName)
    #     if datafilter.count() == 0:
    #         passTranMD5 = hashlib.md5(passWord.encode()).hexdigest()
    #         Login.objects.create(user_name=userName, pass_word=passTranMD5)
    #         return Response(data={'isCreate': True}, status=status.HTTP_200_OK)
    #     return render(request, "Login/loginView.html")


    # đăng nhập
    def post(self, request):
        dataPost = {'user_name': request.data['username'], 'pass_word': request.data['password']}
        mydata = Account(data=dataPost)
        if not mydata.is_valid():
            return Response("data is not validate ", status=status.HTTP_400_BAD_REQUEST)
        userName = mydata.data['user_name']
        passWord = mydata.data['pass_word']
        passTranMD5 = hashlib.md5(passWord.encode()).hexdigest()
        datafilter = Login.objects.filter(user_name=userName, pass_word=passTranMD5)
        if datafilter.count() == 0:
            return render(request, "Login/loginView.html")
        return Response({'isLogin': True}, status=status.HTTP_200_OK)


    # test demo
    # def post(self, request):
    #     mydata = Account(data=request.data)
    #     if not mydata.is_valid():
    #         return Response("data is not validate ", status=status.HTTP_400_BAD_REQUEST)
    #     userName = mydata.data['user_name']
    #     passWord = mydata.data['pass_word']
    #     dataCreate = Login.objects.create(user_name=userName, pass_word=passWord)
    #     return Response(data=dataCreate.id, status=status.HTTP_200_OK)

myProject/mysite/news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .form import PostForm


# Create your views here.

def new(request):
    return render(request, "news/index.html")


def post_News(request):
    a = PostForm()
    return render(request, "news/add_post.html", {'f':a})

def save_news(request):
    if request.method == 'POST':
        p = PostForm(request.POST)
        if p.is_valid():
            p.save()
            return HttpResponse("<h1 style='color: green'>save</h1>")
        else:
            return HttpResponse("<h1 style='color: red'>don't validate !</h1>")
    else:
        return HttpResponse("<h1 style='color: red'>don't method POST !</h1>")

myProject/mysite/poll/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from .models import Question, Login

# Create your views here.
def login(request):
    return render(request, "poll/login.html")


def checkLogin(request):
    user_name = request.POST['username']
    pass_word = request.POST['password']
    return HttpResponse(user_name + " " + pass_word)

def index(request):
    listName = ["Huynh Quang Nam", "Tran Quan Lam", "Hoang Nguyen Luat"]
    return render(request, "poll/index.html", {'listName': listName})


def viewList(request):
    listQuestion = Question.objects.all()
    return render(request, "poll/content_page.html", {'listQuestion': listQuestion})


def detailView(request, question_id):
    q = Question.objects.get(pk=question_id)
    return render(request, "poll/detail_question.html", {'qs': q})


def vote(request, question_id):
    q = Question.objects.get(pk=question_id)
    try:
        re = request.POST["choice"]
        c = q.choice_set.get(pk=re)
    except:
        return HttpResponse("lỗi không có choice nghe chú... check lại nghe!!!!")
    c.votes += 1
    c.save()
    print(q)
    return render(request, "poll/result.html", {'rq': q})

myProject/mysite/Login/templates/Login/loginView.html
{% load static %}
<!doctype html>
<html lang="en-us">
<head>
    <title>Log in </title>
    <link rel="stylesheet" type="text/css" href="{% static 'Login/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Login/login.css' %}">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'Login/responsive.css' %}">
    <meta name="robots" content="NONE,NOARCHIVE">
</head>
<body class=" login" data-admin-utc-offset="0">
<!-- Container -->
<div id="container">
    <!-- Header -->
    <div id="header">
        <div id="branding">
            <h1 id="site-name">
                <a href="{% url 'login' %}">Login</a>
            </h1>
        </div>
    </div>
    <!-- END Header -->
    <!-- Content -->
    <div id="content" class="colM">
        <div id="content-main">
            <form action="{% url 'acc' %}" method="post" id="login-form">
                {% csrf_token %}
                <div class="form-row">
                    <label class="required" for="id_username">Username:</label>
                    <input type="text" name="username"
                           autofocus=""
                           autocapitalize="none"
                           autocomplete="username"
                           maxlength="150" required=""
                           id="id_username">
                </div>
                <div class="form-row">
                    <label class="required" for="id_password">Password:</label>
                    <input type="password" name="password"
                           autocomplete="current-password"
                           required="" id="id_password">
                </div>
                <div class="submit-row">
                    <input type="submit" value="Log in">
                </div>
                <div style="margin-top: 15px;"><a href="#">register an account!</a>
                </div>
            </form>
        </div>
        <br class="clear">
    </div>
    <!-- END Content -->
    <div id="footer"></div>
</div>
<!-- END Container -->
</body>
</html>

myProject/mysite/news/templates/news/add_post.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'news:save' %}" method="post">
        {% csrf_token %}
        <div>{{ f.title }}</div>
        <div>{{ f.content }}</div>
        <div>{{ f.date_time }}</div>
        <input type="submit" value="submit">
    </form>
</body>
</html>

myProject/mysite/news/templates/news/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>index</div>
</body>
</html>

myProject/mysite/poll/templates/poll/content_index.html
{% extends 'poll/index.html' %}

{% block content %}



{% endblock %}

myProject/mysite/poll/templates/poll/content_page.html
{% extends 'poll/index.html' %}

{% block content %}
    {% if listQuestion%}
        {% for item in listQuestion %}
            <a href="{% url 'detail' item.id %}"><div>{{item.question_text}}</div></a>
        {% endfor %}
    {% else %}
        <div class="exception" style="font-size: 20px; font-weight: bold; color: red">404</div>
    {%endif%}
{% endblock %}

myProject/mysite/poll/templates/poll/detail_question.html
{% extends 'poll/index.html' %}

{% block content %}
    {% if qs %}
        <form action="{% url 'vote' qs.id %}" method="post">
            {% csrf_token %}
           {% for item in qs.choice_set.all %}
                <div>
                    <input type="radio" value="{{item.id}}" name="choice" >
                    <label>{{item.choice_text}}</label>
                </div>
            {% endfor %}
            <input type="submit" value="send">
        </form>
    {% endif %}
{% endblock %}

myProject/mysite/poll/templates/poll/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DEMO</title>
</head>
<body>
<!--    {% block header %}-->
<!--    {% endblock %}-->
    <div class="header">
        <div class="carousel"
             style="width: 100%; height: 5rem; background: azure; text-align: center; line-height: 5rem; font-weight: bold; color: antiquewhite ; font-size: 3rem">
            Header
        </div>
        <div class="list-menu"
             style="width: 100%; height:2.5rem; display: flex; justify-content: center; align-items: center">

            <div class="item-menu" style="width: 4rem; font-weight: bold; font-size: 15px">Item 1</div>
            <div class="item-menu" style="width: 4rem; font-weight: bold; font-size: 15px">Item 2</div>
            <div class="item-menu" style="width: 4rem; font-weight: bold; font-size: 15px">Item 3</div>
            <div class="item-menu" style="width: 4rem; font-weight: bold; font-size: 15px">Item 4</div>

        </div>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

myProject/mysite/poll/templates/poll/login.html
{% load static %}
<!doctype html>
<html lang="en-us">
<head>
    <title>Log in </title>
    <link rel="stylesheet" type="text/css" href="{% static 'poll/css-login/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'poll/css-login/login.css' %}">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'poll/css-login/responsive.css' %}">
    <meta name="robots" content="NONE,NOARCHIVE">
</head>
<body class=" login" data-admin-utc-offset="0">
<!-- Container -->
<div id="container">
    <!-- Header -->
    <div id="header">
        <div id="branding">
            <h1 id="site-name">
                <a href="{% url 'login' %}">Login</a>
            </h1>
        </div>
    </div>
    <!-- END Header -->
    <!-- Content -->
    <div id="content" class="colM">
        <div id="content-main">
            <form action="{% url 'check-login' %}" method="post" id="login-form">
                {% csrf_token %}
                <div class="form-row">
                    <label class="required" for="id_username">Username:</label>
                    <input type="text" name="username"
                           autofocus=""
                           autocapitalize="none"
                           autocomplete="username"
                           maxlength="150" required=""
                           id="id_username">
                </div>
                <div class="form-row">
                    <label class="required" for="id_password">Password:</label>
                    <input type="password" name="password"
                           autocomplete="current-password"
                           required="" id="id_password">
                </div>
                <div class="submit-row">
                    <input type="submit" value="Log in">
                </div>
            </form>
        </div>
        <br class="clear">
    </div>
    <!-- END Content -->
    <div id="footer"></div>
</div>
<!-- END Container -->
</body>
</html>

myProject/mysite/poll/templates/poll/result.html
{% extends 'poll/index.html' %}

{% block content %}
    {% if rq %}
        <h1>{{ rq.question_text }}</h1>
        <h2>Vote</h2>
        {% for i in rq.choice_set.all %}
            <div>{{i.choice_text}} : {{i.votes}}</div>
        {% endfor %}
    {% else %}}
        <h1 style="color: red; font-weight: bold;">Chưa có dữ liệu</h1>
    {% endif %}
{% endblock%}